### ISSUE TITLE
Corpus data와 다른 data간의 참조관계 문의

### ISSUE THREAD

**Issue by carrtesy** [lbox-kr/lbox-open#11]
안녕하세요,

lbox corpus / st 데이터를 사용하려는 중 문의사항이 있어 질문드리고자 합니다.

저희가 하고자 하는 부분은 statute classficiation에 있는 사실관계에 대하여, 이 **사실관계에 해당하는 판결문 전체**를 corpus에서 찾고자 하는건데요. 

1. 우선 statute classificaiton의 사실관계에 해당하는 부분을 포함한 판결문을 corpus에서 항상 찾을 수 있나요? test2의 경우 overlap 이 안되어 있다는 dataset description은 확인했는데요, 다른 train/val/test는 어떤지 궁금합니다.
2. 찾을 수 있다면, 어떤 방법으로 찾을 수 있나요? id의 경우 데이터셋간에 통용되는 것이 아니라 특정 데이터 안에서만 통용되는 id인것 같습니다. 
3. 추가적으로, case들의 사건번호 (예를 들어, 2018가합6506과 같은 고유 id) 를 데이터셋에 추가할 계획이 있으실까요?

감사합니다.

**Comment by whwang299** [comment]
안녕하세요 @carrtesy 님

1. 
`statute_classification` 의 `training`, `validation`, `test` set 의 경우(제가 실수가 없었다면) `precedent_corpus`에서 확인 가능하십니다!
`statute_classification_plus`의 경우 후에 `precedent corpus`에 포함될 예정입니다.

2. 사실관계로 matching하실수 있을것 같습니다.

3. 사건번호의 경우 현재는 계획에 없습니다만, 프로젝트를 진행하는데 있어 필요하실지요?

황원석 드림

**Comment by whwang299** [comment]
음.. 1번, 2번 질문 관련하여 프로젝트 진행의 효율성을 위해

`statute_classfication`의 `id`와(`casename_classification`의 `id`와 동일)
 `precedent_corpus`의  `id` 간의 map을 올려드립니다. 

[casename_id_to_precedent_id](https://lbox-open.s3.ap-northeast-2.amazonaws.com/precedent_benchmark_dataset/casename_classification/v0.1.2/casename_id_to_precedent_id.json)

참고되시길 바랍니다.

**Comment by carrtesy** [comment]
아 답변주신 부분을 늦게 확인했습니다. mapping된 json파일이 저희가 딱 원하는 부분이었습니다. 감사합니다.
혹시 추후에 plus 데이터가 corpus에 언제쯤 추가될 예정인지도 알 수 있을까요?

**Comment by whwang299** [comment]
현재로선 여력이 없어.. 아마 이번 학기중에는 힘들것 같습니다;;

**Comment by carrtesy** [comment]
아 네 확인했습니다, 답변 감사드립니다!
