### ISSUE TITLE
No Derivatives License

### ISSUE THREAD

**Issue by Breakend** [lbox-kr/lbox-open#14]
Hi,

I noticed that this dataset is licensed under a No Derivatives license. That might limit the ability to train machine learning models on this data, but doesn't seem to be the intention of the original work. I was wondering if you, the authors, grant permission to users to train machine learning models on the data? Alternatively, is it possible to change the license to a non-ND CC license?

Thanks!

**Comment by whwang299** [comment]
Hi @Breakend 

We have updated the license from `CC BY-NC-ND 4.0` to `CC BY-NC 4.0`. 
Thanks for the comment!

Wonseok
