### ISSUE TITLE
statute_classification data와 statute_classification_plus data간의 관계 문의

### ISSUE THREAD

**Issue by carrtesy** [lbox-kr/lbox-open#17]
안녕하세요,

다름아니라 (1) statute_classificaiton_plus data 안에, statute classification data가 다 포함되어 있는지, (2) 있다면 mapping을 얻을 수 있을지 문의드리고자 합니다.
```python
for d in data_st["train"]:
    f = d["facts"]
    for dp in data_st_plus["train"]:
        if dp["facts"] == f:
            print("found in train")
```
위와 같이 간단하게 for문을 돌려보며 단순하게 사실관계를 비교했을때는 찾지 못하는 경우가 많았는데요, 제 추측으로는 plus set에서 전처리 작업을 더 하셔서 문자열 단순비교가 불가능하지 않나 싶습니다.

혹시 이와 관련하여 답변 주실 수 있을까요?

감사합니다.

**Comment by whwang299** [comment]
안녕하세요 @carrtesy  님, 
확인 감사합니다. 말씀 주신대로, 전처리 과정에서 
New line 및 apostrophe 처리가 바뀐것을 확인했습니다ㅜ(아래 예시 참조).

여기 두 데이터셋 간 mapping 정보 첨부드립니다.
[`statute_classification_id_to_statute_classification_plus_id.json`](https://lbox-open.s3.ap-northeast-2.amazonaws.com/precedent_benchmark_dataset/statute_classification/v0.1.2/statute_id_to_statute_plus_id.json)

2760 개중 111개의 경우 matching이 누락되었는데 추후 보완할 예정입니다.




### 예시

`statute_classification`의 경우
`"피고인은 2021. 7. 9. 02:20경 광주 광산구 B에 있는 광주광산경찰서 C지구대 앞에서, ‘승객이 목적지도 말하지 않고 술에 취해 욕설을 하니 도와 달라'는 성명불상의 택시 기사의 요청에 따라 그 진술을 듣고 있던 위 지구대 소속 경찰공무원인 경위 D(남, 44세)에게 욕설을 하고, 계속하여 D이 피고인에게 귀가를 권유하자 D의 목 부위를 손으로 1회 때려 폭행하였다.\n이로써 피고인은 경찰공무원의 범죄 예방 및 지구대 상황 관리 등에 관한 정당한 직무집행을 방해하였다."`

`statute_classification_plus`의 경우
`'피고인은 2021. 7. 9. 02:20경 광주 광산구 B에 있는 광주광산경찰서 C지구대 앞에서, ‘승객이 목적지도 말하지 않고 술에 취해 욕설을 하니 도와 달라’는 성명불상의 택시 기사의 요청에 따라 그 진술을 듣고 있던 위 지구대 소속 경찰공무원인 경위 D(남, 44세)에게 욕설을 하고, 계속하여 D이 피고인에게 귀가를 권유하자 D의 목 부위를 손으로 1회 때려 폭행하였다. 이로써 피고인은 경찰공무원의 범죄 예방 및 지구대 상황 관리 등에 관한 정당한 직무집행을 방해하였다.'`

**Comment by carrtesy** [comment]
답변 주셔서 감사합니다!
혹시 누락된 111개의 데이터의 경우, 이번 학기 내로 추가하실 계획이 있으실지 여쭤볼 수 있을까요?

**Comment by whwang299** [comment]
이번학기 이후에 추가 가능할것 같습니다;; 
혹시 프로젝트 진행에 중요하다 판단될 경우, 그 이유를 공유해주시면 고려하여 우선순위를 조절해 볼 수 있을것 같습니다!

**Comment by carrtesy** [comment]
아 네네 답변 감사합니다! 저희는 누락된 데이터를 제외하고 우선 진행하면 될 거 같아서요, 우선순위에 두실 필요는 없을 것 같습니다~ 감사합니다.
