### ISSUE TITLE
토크나이저 에러 문의 

### ISSUE THREAD

**Issue by LAB-703** [lbox-kr/lbox-open#22]
안녕하세요 법률 언어모델에 관심이 많아 탐색하던 도중 귀사의 언어모델을 사용해보고 있습니다.
학습과 생성은 잘 되는 거 같은데 토크나이징했을 때 이런 현상이 발생하네요.
확인 부탁드립니다.

tokenizer = transformers.AutoTokenizer.from_pretrained(
    "lbox/lcube-base",
    bos_token="[BOS]",
    unk_token="[UNK]",
    pad_token="[PAD]",
    mask_token="[MASK]",
)
tokenizer.tokenize("누구든지 아동·청소년이용음란물임을 알면서 이를 소지하여서는 아니된다.")

>> ['ĠëĪĦêµ¬',
 'ëĵłì§Ģ',
 'ĠìķĦëıĻ',
 'Â·',
 'ì²Ń',
 'ìĨĮëħĦ',
 'ìĿ´ìļ©',
 'ìĿĮ',
 'ëŀĢ',
 'ë¬¼',
 'ìŀĦ',
 'ìĿĦ',
 'ĠìķĮ',
 'ë©´', ..]

**Comment by whwang299** [comment]
@LAB-703 님 안녕하세요. 

Byte-level BPE 의 특징입니다. 간접적으로 각  token을 확인해 보고 싶을 경우
```
encoded = tokenizer("구든지 아동·청소년이용음란물임을 알면서 이를 소지하여서는 아니된다.")
for input_id in encoded["input_ids"]:
    print(tokenizer.decode(input_id))
```
같이 해보실수 있습니다.

감사합니다.

**Comment by LAB-703** [comment]
빠른 답변 감사합니다.
