### ISSUE TITLE
Statute Classification Dataset 업데이트 문의

### ISSUE THREAD

**Issue by carrtesy** [lbox-kr/lbox-open#8]
안녕하세요,

KAIST 법률인공지능 수업을 수강중인 김동민/양소영/홍지민입니다.

다름아니라 중간 프로젝트 피드백에서 statute classification dataset이 기존 2000여개에서 1만여개 정도로 업데이트 될 것이라고 하였는데요, 업데이트가 언제쯤 가능하실지 여쭙고자 합니다.

혹시 답변 주실 수 있을까요?

감사합니다.

**Comment by whwang299** [comment]
@carrtesy 님, 이미 업데이트 되었습니다!
```
from datasets import load_dataset
data_st_plus = load_dataset("lbox/lbox_open", "statute_classification_plus")
```
와 같이 사용해주시면 됩니다!

**Comment by carrtesy** [comment]
확인했습니다, 감사합니다!
